# Project Configuration File
project:
  name: enterprise-rag
  version: 2.0.0
  description: Enterprise RAG Knowledge Q&A System based on AWS Nova

structure:
  applications:
    backend:
      - lambda: Lambda function code
      - layers: Lambda layers
      - shared: Shared code library
    frontend:
      - React TypeScript application
  
  infrastructure:
    terraform:
      modules:
        - networking: Network module (VPC, subnets, security groups)
        - compute: Compute module (Lambda, API Gateway)
        - storage: Storage module (S3, OpenSearch)
        - security: Security module (WAF, Cognito, IAM)
        - monitoring: Monitoring module (CloudWatch, X-Ray)
      environments:
        - dev: Development environment configuration
        - staging: Staging environment configuration
        - prod: Production environment configuration
  
  scripts:
    deploy: Deployment scripts
    test: Test scripts
    utils: Utility scripts
  
  config:
    environments: Environment configuration files
    secrets: Secret configuration templates
  
  tests:
    unit: Unit tests
    integration: Integration tests
    e2e: End-to-end tests

dependencies:
  python: ">=3.9"
  node: ">=16"
  terraform: ">=1.0"
  aws-cli: ">=2.0"

standards:
  python:
    formatter: black
    linter: flake8
    type_checker: mypy
  
  javascript:
    formatter: prettier
    linter: eslint
    framework: react
  
  terraform:
    version: "~> 1.5"
    formatter: terraform fmt

ci_cd:
  provider: github_actions
  environments:
    - dev
    - staging
    - prod
  
  stages:
    - security_scan
    - lint
    - test
    - build
    - deploy

monitoring:
  cloudwatch:
    namespace: enterprise-rag
    retention_days:
      dev: 7
      staging: 14
      prod: 30
  
  alarms:
    error_threshold: 5
    latency_threshold: 3000
    cost_threshold:
      dev: 500
      staging: 1000
      prod: 2000