# 生产环境配置
environment: prod
region: us-east-1

api:
  endpoint: https://api.enterprise-rag.com
  timeout: 30000
  stage: prod

cognito:
  user_pool_id: ${COGNITO_USER_POOL_ID}
  client_id: ${COGNITO_CLIENT_ID}
  domain: ${COGNITO_DOMAIN}

bedrock:
  model_id: amazon.nova-pro-v1:0
  embedding_model_id: amazon.titan-embed-text-v1
  knowledge_base_id: ${KNOWLEDGE_BASE_ID}
  data_source_id: ${DATA_SOURCE_ID}
  max_tokens: 2000
  temperature: 0.1

s3:
  document_bucket: ${DOCUMENT_BUCKET_NAME}
  frontend_bucket: ${FRONTEND_BUCKET_NAME}

features:
  enable_waf: true
  enable_xray: true
  enable_shield: true
  log_level: INFO
  log_retention_days: 30

monitoring:
  cloudwatch_namespace: enterprise-rag/prod
  alarm_email: ${ALARM_EMAIL}

vpc:
  cidr: 10.1.0.0/16
  public_subnets:
    - 10.1.1.0/24
    - 10.1.2.0/24
    - 10.1.3.0/24
  private_subnets:
    - 10.1.10.0/24
    - 10.1.20.0/24
    - 10.1.30.0/24
  availability_zones:
    - us-east-1a
    - us-east-1b
    - us-east-1c

lambda:
  memory_size: 3008
  timeout: 900
  reserved_concurrent_executions: 100